### ISSUE TITLE
Getting Error During Install on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by sixsamuraisoldier** [devsim/devsim#22]
Here's the error, using the scripts to install:

package_linux.sh: line 1: RC: command not found
must specify dir name

**Comment by tcaduser** [comment]
thanks for finding the error.  I corrected the first line with the proper command, #!/bin/bash, in commit 867aab57c0cf.  Since it is not marked executable by default, you can either:

`
chmod +x package_linux.sh
`

and executing, or execute using:
`
bash package_linux.sh dirname
`

as shown in 

https://github.com/devsim/devsim/blob/master/scripts/build_ubuntu_14.sh

Note that you need to specify a directory name as an argument.

**Comment by sixsamuraisoldier** [comment]
Thanks for the fix! 

When I try to invoke devsim by typing in 'devsim' into terminal I get "devsim: command not found"

This is after using an unofficial docker image as well. Am I doing something wrong here?

BTW, you might want to consider making an unofficial docker image.

**Comment by tcaduser** [comment]
I am not aware of the unofficial docker image.  Where do you find it?

You need to either add the path to devsim to your PATH, or use the full path to the executable.

For example:

`devsim_linux/bin/devsim`

**Comment by sixsamuraisoldier** [comment]
Nevermind, very dumb mistake on my end, typo in the path >.<
