### ISSUE TITLE
[JOSS Review] Confusing multiple documentation sources

### ISSUE THREAD

**Issue by dalonsoa** [devsim/devsim#79]
Part of the review for publication in [JOSS](https://github.com/openjournals/joss-reviews/issues/3898)

It is quite disconcerting that there are two separate documentation sources:
- [DEVSIM TCAD Semiconductor Device Simulator](https://devsim.org/) in https://devsim.org
- [DEVSIM Manual](https://devsim.net/) in https://devsim.net/

The second one is very complete, although although, personally, I would move the release notes towards the end. I am unsure of the purpose of the first one.

I think it will be important, for the sake of clarity, to colapse the above in just one documentation source and  that the entry page is a clear, high level description of what problems the software is designed to solve and who the target audience is. This should also be included in the README file.

**Comment by tcaduser** [comment]
The purpose of the first website (devsim.org) is to be the homepage for the project.  The second website is the documentation, and is generated directly from: https://github.com/devsim/devsim_documentation.  For this reason, I would like to keep them separate.

I have tried to state in the preamble of https://devsim.net the difference between these websites.

Since https://devsim.org is the homepage for the project, it seems this place might be the best to place the motivation for this project.
